---
kind: pipeline
type: kubernetes
name: default

steps:
- name: tests
  image: ruby
  commands:
  - bundle install --jobs=3 --retry=3
  - rake test
- name: sonarqube
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host: http://sonarqube
    sonar_token:
      from_secret: token
    exclusions: "**/*.java"

---
kind: secret
name: token
get:
  path: sonarqube
  name: token
